import type { Metadata } from "next";
import "./globals.css";
import ScreenSizeBadge from "@/components/ScreenSizeBadge";

export const metadata: Metadata = {
  title: "Flowdesk",
  description: "Generated by Ahmed Al-Farouq",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ScreenSizeBadge />
      </body>
    </html>
  );
}
