import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Flowdesk",
  description: "Generated by Ahmed Al-Farouq",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="container min-h-screen  flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
          {children}
        </main>
      </body>
    </html>
  );
}
